inline_chunk_threshold_bytes: null
get_partial_values_concurrency: null
compression: null
max_concurrent_requests: null
caching: null
storage: null
virtual_chunk_containers:
  s3://1deg/:
    name: null
    url_prefix: s3://1deg/
    store: !s3_compatible
      region: null
      endpoint_url: https://projects.pawsey.org.au
      anonymous: false
      allow_http: false
      force_path_style: true
      network_stream_timeout_seconds: 60
      requester_pays: false
manifest: null
